import Navigation from "@/components/Navigation/Navigation";
import Head from "next/head";
import { Box, Center, Container, Grid, Title } from "@mantine/core";
import { Carousel } from "@mantine/carousel";
import Placeholder from "@/components/Placeholder";
import StartCarousel from "@/components/Home/StartCarousel";
import FAQ from "@/components/Home/FAQ";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navigation />
      <StartCarousel />
      <Container size={"90%"}>
        <FAQ />
      </Container>
    </>
  );
}
